# Generated by Django 6.0.2 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='personal_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Personal Email'),
        ),
    ]

