# Generated by Django 6.0.2 on 2026-02-22

import internships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='eligible_batch_years',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed graduation years. Empty means no year restriction.'),
        ),
        migrations.AddField(
            model_name='internship',
            name='eligible_departments',
            field=models.JSONField(blank=True, default=internships.models.default_eligible_departments, help_text='List of allowed departments. Defaults to CSE AIML.'),
        ),
    ]
