# Generated by Django 6.0.2 on 2026-02-04 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('parsed_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resume', to='students.application')),
            ],
            options={
                'db_table': 'parsed_resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortlistingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('cgpa_score', models.FloatField(default=0.0)),
                ('skills_score', models.FloatField(default=0.0)),
                ('experience_score', models.FloatField(default=0.0)),
                ('projects_score', models.FloatField(default=0.0)),
                ('semantic_score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisting_result', to='students.application')),
            ],
            options={
                'db_table': 'shortlisting_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
