# Generated by Django 6.0.2 on 2026-02-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('ml_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedresume',
            name='parse_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shortlistingresult',
            name='certification_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shortlistingresult',
            name='domain_alignment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shortlistingresult',
            name='parser_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='FairnessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('recommended_status', models.CharField(blank=True, max_length=20)),
                ('final_status', models.CharField(blank=True, max_length=20)),
                ('protected_attributes', models.JSONField(default=dict)),
                ('audit_payload', models.JSONField(default=dict)),
                ('identifiers_sanitized', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairness_audit_logs', to='students.application')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fairness_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fairness_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
